### ISSUE TITLE
Duplicating a document

### ISSUE THREAD

**Issue by Nick-h4ck3r** [Nick-h4ck3r/quickflow#6]
Add a feature to **create a duplicate** of the current document. It should create a new document with the name convention "_Copy of [document name]_".

**Please add buttons for this feature in two places:**

1. On the top navigation bar of the document page.
   ![image](https://github.com/user-attachments/assets/bf54fe87-e64d-42ec-b6ab-8a45156440c1)

2. In the sidebar, include this option for each document.
   ![image](https://github.com/user-attachments/assets/1656cda1-1537-4813-b05a-2a903e892133)

**Comment by Dharmik3** [comment]
Hey @Nick-h4ck3r I'm working on it, please assign to me this task

**Comment by Nick-h4ck3r** [comment]
Thanks for the PR @Dharmik3! 🥂

**Comment by Dharmik3** [comment]
@Nick-h4ck3r  Looking forward to more contribution in open source
