### ISSUE TITLE
Unhandled Runtime Error during setup the project in local system.

### ISSUE THREAD

**Issue by Amarsingh2003** [Nick-h4ck3r/quickflow#8]
As per the documentation I set up the project and created the env file and put the value of all variables present in the .env file then I ran the command to launch the site but it gave fetch 404 error.

![image](https://github.com/user-attachments/assets/94ffe889-de45-4ab3-8269-6918aa28d925)

In console it show

![image](https://github.com/user-attachments/assets/18cb043e-f197-46e5-9f5d-376e301145a5)

In network tab:-

![image](https://github.com/user-attachments/assets/c8cbebd6-ec9f-4aef-921c-1ca446febc11)

Please help me to resolve this issue and i  already check my .env file variables which are correct.

**Comment by Dharmik3** [comment]
Yes, similar error I got while locally setting up @Nick-h4ck3r any idea?

**Comment by Nick-h4ck3r** [comment]
Hey, I've updated the readme with proper instructions. Can you try it, and let me know if it works?

Here are the steps: https://github.com/Nick-h4ck3r/quickflow?tab=readme-ov-file#setting-up-the-project-locally

**Comment by Dharmik3** [comment]
Hey, It's working now
